eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8761/eureka/
    instance:
      prefer-ip-address: true #是否映射IP，访问路径时会显示IP
server:
  port: 8765
spring:
  application:
    name: service-feign
  zipkin:
    base-url: http://localhost:9411
feign:
  hystrix:
    enabled: true #在D版本的Spring Cloud之后打开断路器，默认没打开
