server:
  port: 8761

eureka:
  instance:
    hostname: localhost #eureka服务端的实例名称
#    enable-self-preservation: false #false关闭eureka自我保护机制
  client:
    registerWithEureka: false #false表示不向注册中心注册自己。
    fetchRegistry: false #false表示自己端就是注册中心，我的职责就是维护服务实例，并不需要去检索服务
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
      #设置与Eureka Server交互的地址查询服务和注册服务都需要依赖这个地址（单机）。
spring:
  application:
    name: eurka-server
